name: 'Test provider'
description: 'Try to initialize a Magic Castle provider folder'
inputs:
  provider:
    description: 'name of the provider'
    required: true
runs:
  using: "composite"
  steps:
      - run: terraform -chdir=${{ inputs.provider }} init
        shell: bash
        id: init
      - run: terraform  -chdir=${{ inputs.provider }} validate
        shell: bash
        id:
      - run: find examples -name ${{ inputs.provider }} -type d -not -path '*/\.*'
        shell: bash
        id: find-examples
      - run: sed -E -i 's;(source)\s*=.*${{ inputs.provider }}.*;\1 = "../../${{ inputs.provider }}";g' examples/${{ inputs.provider }}/main.tf;
        shell: bash
        id: sed-example
      - run: terraform -chdir=examples/${{ inputs.provider }} init
        shell: bash
        id: init-example
      - run: terraform -chdir=examples/${{ inputs.provider }} validate
        shell: bash
        id: validate-example