variable "cluster_name" {}
variable "domain" {}
variable "instances" {}
variable "volumes" {}
variable "pool" {}
variable "firewall_rules" {}
variable "min_disk_size" {}
variable "image" {}
variable "bastion_tags" {}