variable "instances" { }
variable "volume_devices" { }
variable "sudoer_username" { }
variable "cluster_name" { }
variable "domain_name" { }
variable "guest_passwd" { }
variable "nb_users" { }
variable "software_stack" { }
variable "cloud_provider" { }
variable "cloud_region" { }
variable "tf_ssh_key" { }
variable "hieradata" { }
variable "public_keys" { }
