mod 'puppetlabs-firewall', '1.12.0'
mod 'puppetlabs-stdlib', '4.25.1'
mod 'puppetlabs-concat', '4.2.1'
mod 'derdanne-nfs', '2.0.9'
mod 'yelp-netstdlib', '0.0.1'
mod 'petems-swap_file', '4.0.0'
mod 'herculesteam-augeasproviders_sysctl', '2.2.0'
mod 'herculesteam-augeasproviders_core', '2.1.5'